name: pipeline

on:
  push:
    branches:
      - "develop"
      - "release"
      - "main"
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set common env
        run: |
          echo "PROJECT_NAME=maple_dfu" >> $GITHUB_ENV
          echo "RELEASE_DIRECTORY=./" >> $GITHUB_ENV

      - name: Set alpha env
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          echo "RELEASE_PRE=true" >> $GITHUB_ENV
          echo "RELEASE_SUFFIX=alpha" >> $GITHUB_ENV
          echo "RELEASE_KIND=pre-release" >> $GITHUB_ENV
          
      - name: Set beta env
        if: ${{ github.ref == 'refs/heads/release' }}
        run: |
          echo "RELEASE_PRE=true" >> $GITHUB_ENV
          echo "RELEASE_SUFFIX=beta" >> $GITHUB_ENV
          echo "RELEASE_KIND=pre-release" >> $GITHUB_ENV

      - name: Set release env
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "RELEASE_PRE=false" >> $GITHUB_ENV
          echo "RELEASE_SUFFIX=beta" >> $GITHUB_ENV
          echo "RELEASE_KIND=release" >> $GITHUB_ENV

      - name: Create TAG
        id: tag
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main' }}
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: ${{ env.RELEASE_PRE }}
          PRERELEASE_SUFFIX: ${{ env.RELEASE_SUFFIX }}

      - name: Archive build
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main' }}
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: ${{ env.RELEASE_DIRECTORY }}
          filename: ${{ env.PROJECT_NAME }}_${{ steps.tag.outputs.new_tag }}.zip

      - name: Create release
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ env.RELEASE_PRE }}
          body_path: ${{ github.workspace }}/CHANGES.md
          name: ${{ env.RELEASE_KIND }} ${{ steps.tag.outputs.new_tag }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: |
            ./${{ env.RELEASE_DIRECTORY }}/${{ env.PROJECT_NAME }}_${{ steps.tag.outputs.new_tag }}.zip